# Generated by Django 5.0 on 2025-08-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_timelineentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineentry',
            name='icon',
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='timeline_icons/'),
        ),
    ]
