# Generated by Django 5.0 on 2025-08-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
