# Generated by Django 5.0 on 2025-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
    ]
