# Generated by Django 5.0 on 2025-08-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
    ]
