# Generated by Django 5.0 on 2025-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_remove_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text='Image shown on hover', null=True, upload_to='skill_images/'),
        ),
    ]
