# Generated by Django 5.0 on 2025-08-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_skill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
    ]
