# Generated by Django 5.0 on 2025-08-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0015_timelineentry_link_timelineentry_link_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
